require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

def ccache_enabled?(podfile_properties)
  # Environment variable takes precedence
  return ENV['USE_CCACHE'] == '1' if ENV['USE_CCACHE']

  # Fall back to Podfile properties
  podfile_properties['apple.ccacheEnabled'] == 'true'
end

def strip_duplicate_prebuilt_react_swiftui_linkage!(installer, aggregate_target_name)
  return unless ENV['RCT_USE_PREBUILT_RNCORE'] == '1'

  installer.aggregate_targets.each do |aggregate_target|
    next unless aggregate_target.name == aggregate_target_name

    aggregate_target.xcconfigs.each_value do |xcconfig|
      other_ldflags = xcconfig.attributes['OTHER_LDFLAGS']
      next unless other_ldflags&.include?('-framework "React"')

      sanitized = other_ldflags
        .gsub(/\s-l"RCTSwiftUIWrapper"(?=\s|$)/, '')
        .gsub(/\s-l"RCTSwiftUI"(?=\s|$)/, '')
        .squeeze(' ')
        .strip
      xcconfig.attributes['OTHER_LDFLAGS'] = sanitized
    end
  end
end

ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] ||= podfile_properties['EX_DEV_CLIENT_NETWORK_INSPECTOR']
ENV['RCT_USE_RN_DEP'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true'
ENV['RCT_USE_PREBUILT_RNCORE'] ||= '1' if podfile_properties['ios.buildReactNativeFromSource'] != 'true'
ENV['RCT_HERMES_V1_ENABLED'] ||= '1' if podfile_properties['expo.useHermesV1'] == 'true'
platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'

prepare_react_native_project!

target 'OpenClawMobile' do
  use_expo_modules!
  pod 'JitsiWebRTC', :podspec => File.join(__dir__, 'Podspecs', 'JitsiWebRTC.podspec')
  pod 'ZXingObjC/OneD', :podspec => File.join(__dir__, 'Podspecs', 'ZXingObjC.podspec')
  pod 'ZXingObjC/PDF417', :podspec => File.join(__dir__, 'Podspecs', 'ZXingObjC.podspec')

  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(\'expo/bin/autolinking\')',
      'expo-modules-autolinking',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end

  config = use_native_modules!(config_command)

  use_frameworks! :linkage => podfile_properties['ios.useFrameworks'].to_sym if podfile_properties['ios.useFrameworks']
  use_frameworks! :linkage => ENV['USE_FRAMEWORKS'].to_sym if ENV['USE_FRAMEWORKS']

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :privacy_file_aggregation_enabled => podfile_properties['apple.privacyManifestAggregationEnabled'] != 'false',
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => ccache_enabled?(podfile_properties),
    )
    strip_duplicate_prebuilt_react_swiftui_linkage!(installer, 'Pods-OpenClawMobile')
  end
end
