listening-ip=0.0.0.0
listening-port=${TURN_PORT}
tls-listening-port=${TURN_TLS_PORT}

fingerprint
lt-cred-mech
realm=${TURN_DOMAIN}
server-name=${TURN_DOMAIN}
user=${TURN_USERNAME}:${TURN_PASSWORD}

external-ip=${TURN_PUBLIC_IP}
min-port=${TURN_MIN_PORT}
max-port=${TURN_MAX_PORT}

no-cli
no-tls
no-dtls

pidfile=/var/tmp/turnserver.pid
log-file=stdout
simple-log
